### ISSUE TITLE
你好，我想问下优酷ccode：01010101的问题

### ISSUE THREAD

**Issue by JieGengs** [airdge/VideoParse#1]
我看到有的人能使用ccode：01010101解析成功了，我这个解析不了是什么问题？https://ups.youku.com/ups/get.json?vid=XMzg1OTUxMTY5Mg==&ccode=01010101&client_ip=192.168.1.1&client_ts=1539925156.233&utid=W8j0JAEe2xMDANWPAkWZ0fsB&ckey=7B19C0AB12633B22E7FE81271162026020570708D6CC189E4924503C49D243A0DE6CD84A766832C2C99898FC5ED31F3709BB3CDD82C96492E721BDD381735026

**Comment by JieGengs** [comment]
这是utid的获取方法
function generateUtdid(){
    $timestamp = time() - 60 * 60 * 8;
    $i31 = rand(0, (1 << 31) - 1);
    $imei = hashCode((string)$i31);
    $msg = pack('N2C2N', $timestamp, $i31, 3, 0, $imei);
    $key = 'd6fc3a4a06adbde89223bvefedc24fecde188aaa9161';
    $data = hash_hmac('sha1',$msg,$key,true);
    $msg .= pack('N*', hashCode(base64_encode($data)));
    return base64_encode($msg);
}
function intval32($num) {
 $num = $num & 0xffffffff;//消掉高32位   
 $p = $num>>31; //取第一位 判断是正数还是负数
 if($p==1) { //负数
 $num = $num-1;
 $num = ~$num; //取反 会当成64位取反,算出来的数就去了,所以取反之后 要消掉 高32位
 $num = $num & 0xffffffff;
 return $num * -1;
 } else {
 return $num;
 }
 } 
function hashCode($str){
    $res = intval32(0);
    $str = getBytes($str);
    foreach ($str as $key => $value) {
       $res = intval32(intval32($res * 0x1f) + $value);
	} 
    return $res;
}
function getBytes($string) {
        $bytes = array(); 
        for($i = 0; $i < strlen($string); $i++){ 
             $bytes[] = ord($string[$i]); 
        } 
        return $bytes; 
}

**Comment by airdge** [comment]
这个01010101好像不能带默认ckey
```
ccode=>03020101
referer=>https://v.youku.com/
```

**Comment by JieGengs** [comment]
03020101好像也不行，你有没有测试地址？

**Comment by airdge** [comment]
```
<?php
$vid = 'XMzg1OTUxMTY5Mg==';
$ccode = '03020101';
$url = 'http://ups.youku.com/ups/get.json?vid=' . $vid . '&ccode=' . $ccode . '&client_ip=192.168.1.1&client_ts=' . time() . '&utid=' . urlencode(generateUtdid()) . '&ckey=7B19C0AB12633B22E7FE81271162026020570708D6CC189E4924503C49D243A0DE6CD84A766832C2C99898FC5ED31F3709BB3CDD82C96492E721BDD381735026';
$params = array('referer' => 'https://v.youku.com/');
echo curl($url, $params);

function curl($url, $params = [])
{
    extract($params);
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $referer ? curl_setopt($ch, CURLOPT_REFERER, $referer) : '';
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    $src = curl_exec($ch);
    curl_close($ch);
    return $src;
}
```

响应
`{"cost":0.01600000075995922,"data":{"preview":{"thumb":["http://g3.ykimg.com/052100055BC06750ADA4C71AC20CE1CF","http://g3.ykimg.com/052101055BC06750ADA4C71AC20CE1CF","http://g2.ykimg.com/052102055BC06750ADA4C71AC20CE1CF","h...................{"ctype":"story","start":"2147661","title":"罗维劝说同创业 郭鑫年受打击拒绝","desc":""}]},"stream":[{"audio_lang":"guoyu","milliseconds_audio":2714970,"milliseconds_video":2714929,"segs":[{"size":19486779,"cdn_url":"http://vali.cp31.ott.cibntv.net/6773EA2AE77377160763335A1/03000A07005BC10631FD7E5011BA6A53A27D80-FBEC-4E1B-A66E-BE38EB5A28AE.mp4?ccode=03020101&duration=393&expire=18000&psid=09d0dab94a199a4b878272247e588cce&ups_client_netip=.....`

**Comment by JieGengs** [comment]
确实有用，好像是我curl函数有问题，才导致没返回数据。
public static function curl($url,$params=array())
  {
      $ip = empty($params["ip"]) ? self::rand_ip() : $params["ip"]; 
      $header = array('X-FORWARDED-FOR:'.$ip,'CLIENT-IP:'.$ip);
      if(isset($params["httpheader"])){
        $header = array_merge($header,$params["httpheader"]);
      }
      $referer = empty($params["ref"]) ? $url : $params["ref"];
      $user_agent = empty($params["ua"]) ? $_SERVER['HTTP_USER_AGENT'] : $params["ua"] ;
      
      $ch = curl_init();                                                      //初始化 curl
      curl_setopt($ch, CURLOPT_URL, $url);                                    //要访问网页 URL 地址
      curl_setopt($ch, CURLOPT_HTTPHEADER, $header);                          //伪装来源 IP 地址
      curl_setopt($ch, CURLOPT_REFERER, $referer);                            //伪装网页来源 URL
      curl_setopt($ch, CURLOPT_USERAGENT,$user_agent);                        //模拟用户浏览器信息
      curl_setopt($ch, CURLOPT_NOBODY, false);                                //设定是否输出页面内容
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);                         //返回字符串，而非直接输出到屏幕上
      curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, false);                        //连接超时时间，设置为 0，则无限等待
      curl_setopt($ch, CURLOPT_TIMEOUT, 3600);                                //数据传输的最大允许时间超时,设为一小时
      curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);                       //HTTP验证方法
      curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);                        //不检查 SSL 证书来源
      curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);                        //不检查 证书中 SSL 加密算法是否存在
      curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);                         //跟踪爬取重定向页面
      curl_setopt($ch, CURLOPT_AUTOREFERER, true);                            //当Location:重定向时，自动设置header中的Referer:信息
      curl_setopt($ch, CURLOPT_ENCODING, '');                                 //解决网页乱码问题
      curl_setopt($ch, CURLOPT_HEADER, empty($params["header"])?false:true);  //不返回 header 部分
      if(!empty($params["fields"])){
        curl_setopt($ch, CURLOPT_POST, true);                                  //设置为 POST 
        curl_setopt($ch, CURLOPT_POSTFIELDS,$params["fields"]);                //提交数据
      }
      if(!empty($params["cookie"])){
        curl_setopt($ch, CURLOPT_COOKIE, $params["cookie"]);                  //从字符串传参来提交cookies
      }
      if(!empty($params["proxy"])){
        curl_setopt($ch, CURLOPT_PROXYAUTH, CURLAUTH_BASIC);                  //代理认证模式
        curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP);                  //使用http代理模式
        curl_setopt($ch, CURLOPT_PROXY, $params["proxy"]);                    //代理服务器地址 host:post的格式
        if(!empty($params["proxy_userpwd"])){
            curl_setopt($ch, CURLOPT_PROXYUSERPWD, $params["proxy_userpwd"]); //http代理认证帐号，username:password的格式
        }
      }
      $data = curl_exec($ch);                                                 //运行 curl，请求网页并返回结果
      curl_close($ch);                                                        //关闭 curl
      return $data;
  }
function curl($url, $cookie = "") {
    $params["ua"] = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36";
    $params["ref"] = "https://v.youku.com";
    $params["cookie"] = $cookie;
    return GlobalBase::curl($url, $params);
}
我当时用的是这个，这个好像有问题

**Comment by JieGengs** [comment]
你好，您能不能加一个 的联系方式？
