### ISSUE TITLE
优酷ccode0502

### ISSUE THREAD

**Issue by JieGengs** [airdge/VideoParse#2]
我看到ykdl也更新了0502，但是我使用后都是提示用户账号异常https://ups.youku.com/ups/get.json?vid=XMjg5NzgyNjA5Mg==&ccode=0502&client_ip=192.168.1.1&client_ts=1540255310.763&utid=TlxVFHKRciYCASdrU7xYAY2e&ckey=7B19C0AB12633B22E7FE81271162026020570708D6CC189E4924503C49D243A0DE6CD84A766832C2C99898FC5ED31F3709BB3CDD82C96492E721BDD381735026
但是我看到有的人0502有效

**Comment by airdge** [comment]
使用同个cKey会有频率限制,访问多次后就会提示账户异常
目前有效是及时生成ckey(112#/110#)  或者带cookies访问  这两种都能获取到数据
如果上面两种形式无法满足,那只能挂代理ip

**Comment by airdge** [comment]
腾讯分段和单段mp4都要经过行为上报才不会限速
具体可以抓包js找下report过程

**Comment by airdge** [comment]
那就是没上报完整,有些上报是播放不卡,有些是解除同个ip上报限制

**Comment by JieGengs** [comment]
$xq = date("w");
$enver = '7.'.$xq;
if($enver=='7.1'){
	$key = "06fc1464";
}elseif($enver=='7.2'){
	$key = "4244ce1b";
}elseif($enver=='7.3'){
	$key = "77de31c5";
}elseif($enver=='7.4'){
	$key = "e0149fa2";
}elseif($enver=='7.5'){
	$key = "60394ced";
}elseif($enver=='7.6'){
	$key = "2da639f0";
}else{
	$enver = '7.7';
	$key = "c2f0cf9f";
}
$ckey = md5("$key$vid$t*#06#$plat");
$url = "http://h5vv.video.qq.com/getvkey?charge=0&otype=ojson&platform=$plat&sdtfrom=$sdt&appVer=3.4.9&tm=$t&vid=$vid&defn=shd&format=2&filename={$vid}.mp4&ehost=https%3A%2F%2Fv.qq.com&encryptVer=$enver&cKey=$ckey";
我看到有人在getvkey加了ckey这个参数，这个重要吗？

**Comment by JieGengs** [comment]
_qv_rmt和_qv_rmt2这2个参数好像也有说是影响限速的原因

**Comment by airdge** [comment]
_qv_rmt是很早前的算法,应该失效了,也不管用
getvkey接口必须加cKey参数
