### ISSUE TITLE
优酷这个接口你用过吗？

### ISSUE THREAD

**Issue by JieGengs** [airdge/VideoParse#3]
http://tv.api.3g.youku.com/v3/common/h265/play?id='.$vid.'&format=1,5,6,7,8&ctype=30&streamcoding=h264&dq=mp4&pid=65a965fbf632be6f&guid=
接口有些参数我不知道。最近获取不到数据了
就是类似下面的这种播放地址
http://pl.cp31.ott.cibntv.net/playlist/m3u8?ts=1540378062&keyframe=0&m3u8Md5=e0eed7b041133d3b6cf3b051ab06a87b&vid=XMjg5NzgyNjA5Mg==&type=hd3&ctype=30&sid=0540378062909309c04cb

**Comment by JieGengs** [comment]
http://tv.api.3g.youku.com/v3/common/h265/play?id=XMjQ5MjQwNDAwNA==&format=1,5,6,7,8&point=1&language=guoyu&cl=0&site=1&position=7&is_fullscreen=0&player_type=tvdevice&sessionid=3D9A2665D477E019&device_type=tv&device_brand=samsung&aw=a&rst=m3u8&mac=02%3A00%3A00%3A00%3A00%3A00&version=1.0&ctype=30&did=3a66405d00839be94778bf0b00091b38&ouid=&hd3_limit=0&streamcoding=h264&dq=mp4&preload=0&with_channel=0&adext=&serial=0&appsign=0ffe0b6be568508f6d24c54fcec5e925&pid=9b03e6d598427330&guid=3a66405d00839be94778bf0b00091b38&ngdid=7a0f248d2182d4d90268e61e5b6c2b8d&ver=5.0.1&network=WIFI&packagename=com.youku.tv.c&ua=SM-G935F&sdk=2.1.0.720&ppid=f54b313db184bb16&uuid=unknow_tv_imei&chip=0&media=default&mdl=SM-G935F&osv=7.0&os=Android&dvw=1920&dvh=1080&dprm=2625&im=&aid=3242d01b69d76769&sign=zVK8L2pYhxGLwuSvT3dcakZAKzI=
这个接口是我之前在google上面搜到的，之前能使用，现在不能用了，是pid的问题吗？

**Comment by airdge** [comment]
如果参数都改动了还是不行,估计得带cookies了

**Comment by JieGengs** [comment]
ccode:  0103010102   的ua用这个OTTSDK;2.0.3.73;Android;4.4.2;oppo R11竟然不加cookie也能使用。
http://tv.api.3g.youku.com/v3/common/h265/play?id=这个接口主要是我自己也不知道哪些参数是变的，pid好像是在源代码里面，别的我就不清楚了

**Comment by airdge** [comment]
ups接口一般限制useragent/referer/ckey/cookies

自己的下载器用的是解析ckey(110#)算法,一直没问题,不用你们那么麻烦,天天改ccode

**Comment by JieGengs** [comment]
$ckey_m = "110#j4UkAUkfkdrOu0L82wgAMuy2kMUyfFGOmkm2hQ7/8DBLkPGMJx2IjQmkFXCS+MzQmakbhgJy8pcijkLaqMuySg3gkR5t81GOmJScScUIbRjIuRadzDmhUoRGIdEcOeLPMyZGlLvwsTvsQEbllAciskT47Tmwj3k4mPW3sGbLUTZI4yjOCxTQsFpaGLcOjTcw4w23sLFgsjgUkcaOs3rXzy1dSPtHpur/ak237kfFX/h32wHakT65FNgZWTcgPzUT+q10IKa92o1izzNnFN+DeHtS2e9nWRjvLaKYwvOesI98g1GoEXAhiOKBhAQ17pMvEHNhyb9jzGWuG+E/zqc9FCP0lG1YVd6HGqn+09LN6fwPm1EkoOmZLxIThxSPzMult7UdGTDZjfkE3iV5OTR4Ymmc86p4va2MvijtO9YbRp0ZaKuR8LVLCMRJWBnGQpRr2sKAc6DWoR9iOBGbX6CQbla=#0";
我尝试过这个，好像也没用。
你的下载器是哪个？
有没有案例可以给我看看

**Comment by airdge** [comment]
本地下载器,线上没有部署  
使用过的ckey有限制,ckey要及时生成

**Comment by airdge** [comment]
可以用phantomjs跑网页,或者nodejs来运行
不过难度相对较大
`https://aeu.alicdn.com/js/cj/110.js`
这个是ckey的js,可以拿去练练手

**Comment by wuxing164** [comment]
ckey(110#)通过110.js 怎么获取的，调用哪个方法？

**Comment by wuxing164** [comment]
ckey(110#)获取,一般可以使用phantomjs/webdriver,或者nodejs跑js获取 ,是跑哪个JS调哪个方法获取的？

**Comment by wuxing164** [comment]
window[window.UA_Opt.LogVal] 这个好似是ckey 不太确定。

**Comment by airdge** [comment]
现在是
` http://aeu.alicdn.com/AWSC/uab/113.js?d=24`
不同ckey版本跑动的方法和参数稍微有点不同
具体细节,请自行抓包
window[window.UA_Opt.LogVal] 这个就是获取ckey的

**Comment by JieGengs** [comment]
优酷cookie     _m_h5_tk=;_m_h5_tk_enc=;这2个是访问页面获取的还是有一定的规律？

**Comment by JieGengs** [comment]
https://cdn.jsdelivr.net/gh/prince3661/age23@7/ckey2.js   最近有人公开了var ckey=i(10,e);可以获取ckey

**Comment by airdge** [comment]
那个是格式化过的https://aeu.alicdn.com/js/cj/112.js


访问acs.youku.com接口就会生成 _m_h5_tk和_m_h5_tk_enc

**Comment by airdge** [comment]
链接及其参数 以抓包为准
```
var https = require("https");
var urls = require("url");


var acs = 'https://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/?jsv=2.4.16&appKey=24679788';
getHeaders(acs, function(res) {
    console.log(res['set-cookie'])
});

function getHeaders(t, a) {
    var e, o, h;
    h = "object" == typeof t ? t.url : t, "http" != h.substr(0, 4) && (h = "http:" + h), e = urls.parse(h);
    var n = e.hostname,
        d = e.path,
        p = {
            hostname: n,
            path: d,
            method: t.method || "GET"
        };
    o = "https:" == e.protocol ? https : http, t.headers && (p.headers = t.headers), o.get(p, function(t) {
        data = "", t.on("data", function(t) {
            data += t
        }), t.on("end", function() {
            a(t.headers);
        })
    })
}
```

响应:

```
[ '_m_h5_tk=70a57606f0cxxxxx_15411319xxxx; Domain=youku.com; Expires=Sat, 03-Nov-2018 02:54:43 GMT; Path=/',
  '_m_h5_tk_enc=c18066a1c4c2exxxxc; Domain=youku.com; Expires=Sat, 03-Nov-2018 02:54:43 GMT; Path=/' ]
```

**Comment by JieGengs** [comment]
我看到有人的写法是下面这种，不知道他这是想干嘛
function cccc(t) {
            var e = new RegExp("(?:^|;\\s*)" + t + "\\=([^;]+)(?:;\\s*|$)").exec(h5_tk);
            return e ? e[1] : void 0
}
var h5_tk='_m_h5_tk=289baa00d61891e447b93e2c74063c85_1541136772382;_m_h5_tk_enc=ce7bef1c5c79c3bc45281fd347f644be;';
var h5_tk=cccc('_m_h5_tk').split("_")[0];
他在下面调用了h5_tk，不知道这个参数的值是哪个
var sign = s(h5_tk+ "&" + l + "&" + a + "&" + data);

**Comment by airdge** [comment]
[https://github.com/zhangn1985/ykdl/issues/270](https://github.com/zhangn1985/ykdl/issues/270)

**Comment by wuxing164** [comment]
ups.youku.com/ups/get.json   ccode 用0519 需要带什么cookie 可以获取到完整的视频？

**Comment by wuxing164** [comment]
ups.youku.com/ups/get.json ccode 用0519 需要带什么cookie 可以获取到完整的视频？ 用112.js的ckey可以吗？

**Comment by JieGengs** [comment]
搜狐视频上报了下面这个地址，感觉还是有点卡顿是什么问题？
http://z.m.tv.sohu.com/h5_cc.gif?t='.time().'1735&uid='.$sohu_uri.'&position=play_verify&op=click&details={"columnId":"332"}&nid=&url=http://m.tv.sohu.com/v3806134.shtml?aid=9350920&channeled=1910000001&columnid=332&refer=http://m.tv.sohu.com/film&screen=360x640&os=android&platform=android&passport=&vid=3806134&pid=9350920&channeled=1910000001&MTV_SRC=10010001

**Comment by airdge** [comment]
[https://github.com/zhangn1985/ykdl/issues/318](https://github.com/zhangn1985/ykdl/issues/318)
