### ISSUE TITLE
咨询下，ccode 0516 ckey乱输 也能拿到连接地址，没找到什么规律

### ISSUE THREAD

**Issue by wuxing164** [airdge/VideoParse#4]
ccode 0516 ckey乱输 也能拿到连接地址，没找到什么规律，ckey好似也不是必输的。还是不清楚是什么关系。
还有qq的上报是什么意思 ？

**Comment by airdge** [comment]
0516属于预览ccode,其能解析到的数据本就不完整
和ccode=0590一样,带不带ckey都可以解析到数据
对于一些网页类的ccode,ckey也不是必要参数,只是不带ckey参数,限制会比较多,解析没几次就提示登录账户

直接通过api去解析qq视频,获取到的链接是限速的,
这是因为在解析过程中少了一系列认证流程,只有跑了这些认证流程,解析到的链接才不会卡顿
这个过程就是该解析的行为上报/report

**Comment by wuxing164** [comment]
大神好厉害 能不能指点下我啊。。。现在那个ccode能拿 到完整的视频 ，我答合ckey去取，ckey可以调用window[window.UA_Opt.LogVal] 来获取~

**Comment by airdge** [comment]
全长:0502/0511/0512/0515/0519... 预览:0505/0503/0516/0517/0590..

**Comment by wuxing164** [comment]
https://ups.youku.com/ups/get.json?vid=XMzgzMjk2NzEyNA==&ccode=0519&client_ip=192.168.1.1&client_ts=1540897399.879&utid=eShfFNbpYV8CAQ7b7vLhWWPD&ckey=113%23QX47qffFfu9yOa4AvdYb16F6bOu%2Fz5HqDskWk0inosbxbY4kY7Cf1zdGUWiYsPDNDP56zb9h6oBfbXxOkWAD1PF6bFiYs6k8DYkNxW9wos9xwqNqwD5o1%2BjWbFbOsPkWDYuLk0w2uXbkHdKLO0HD1Pf6ikY81u7vIjCl59DNWC0XPizPosQtCoe6WeNq1igv%2Bv6tz9kN9R0cO97uNGPJHh1APOh1yLcHATBGPm4b7kz8%2FEZwfdV0kD41t7GGZm%2FTpKekH10v%2B%2BmgGTo6fKrzwqHoecly58n0mvmAnYvA%2BjeiBg4R%2FLUHX5DHirxsoQefzcDIwfCO9ID7IWfUCYqQxyIZLhkpkGYa5bvKU8lvQ6uGjX0SrJABIc9uZW2ejp%2FDL10LBSaoe2GRIg7W%2BtuwtLV8UnfMRNTMKelcTZb3C4W2hHgLV0nwwPQzXL8z9CPgjKYzLrTZVFRnZreI98JZXHRtxeyykD0k15VAdLLZtTuiVHM8xdIVbwMGmgKAao3Z%2BhBT


用户账户异常、请重新登录 这种怎么破~

**Comment by wuxing164** [comment]
ckey是用window[window.UA_Opt.LogVal] 获取的

**Comment by wuxing164** [comment]
client_ip 改成0.0.0.0就可以了~~ ckey好似可以重用~

**Comment by airdge** [comment]
ckey能不能复用 你多刷新几次就知道了 
一般会先有数据 然后提示账户异常 再客户端无权播放

**Comment by wuxing164** [comment]
真的又用户账户异常、请重新登录。。这种情况 我换ckey 还是报异常，求解~~

**Comment by wuxing164** [comment]
现在测试 拿 网页的cckey来测的。。

**Comment by airdge** [comment]
之前script标签直接引用js跑的ckey   在ccode=0515下是获取不到数据的
替换成在优酷下获取的ckey却可以,
不太清楚你拿的是哪个数据的ckey
如果是直接调用js获取的ckey,限制会比官方来的多
